###################################################
# BUILT-IN CONFIGURATION OPTOINS                  #
# https://gohugo.io/getting-started/configuration #
###################################################

baseURL = "https://mwflower.github.io"
disqusShortname = ""                      # disqus shortcode
enableGitInfo = false                     # retrieve last modified date from git commits
enableRobotsTXT = true                    # /robots.txt
googleAnalytics = ""                      # google analytics id
hasCJKLanguage = true                     # Chinese/Japanese/Korean
languageCode = "en"                       # content language
paginate = 5                              # number of posts each page
rssLimit = 10                             # maximum items in rss feeds
theme = "texify"               # theme directory name
title = "Run"                          # website title

[author]
email = "me@example.com" # your email
name = "author"          # your name

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true # enable html in markdown
[markup.highlight]
style = "emacs" # syntax highlight style, see https://xyproto.github.io/splash/docs/

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/post/"
    weight = 1
[[menu.main]]
    identifier = "run"
    name = "Run"
    url = "/run/"
    weight = 2

[[menu.main]]
    identifier = "beauty"
    name = "Beauty"
    url = "/gallery/"
    weight = 5

[[menu.main]]
    identifier = "box"
    name = "Box"
    url = "/box/"
    weight = 10

[[menu.main]]
    identifier = "station"
    name = "Station"
    url = "/station/"
    weight = 15

[taxonomies]
series = "series" # see https://gohugo.io/templates/internal/#open-graph
tags = "tags"


########################
# TEXIFY THEME OPTIONS #
########################

[params]
description = "天行健，君子以自强不息" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = """
Welcome
""" # notes in the website footer
keywords = ["run"] # website keywords

customCSS = []            # path to custom css files, relative to ./static
customJS = []             # path to custom js files, relative to ./static
dateFormat = "2006-01-02" # date format, see https://gohugo.io/functions/format/
fullTextRSS = true        # output full-text (instead of only summary) rss
emphasisWithDots = true   # use dots to emphasize chinese texts, see https://zh.wikipedia.org/wiki/%E7%9D%80%E9%87%8D%E5%8F%B7
since = "2024"            # website created year
toc = true               # whether to enable table of contents in posts

# https://giscus.app
[params.giscus]
enable = false # whether to enable giscus
# paste giscus' <script></script> configuration between the triple quotes
script = """
"""

[params.math]
enable = false # whether to enable math typesetting
use = "katex"  # katex or mathjax

[params.outdated]
enable = false # whether to display warnings for outdated posts
limit = 1000   # days between last modified time and outdated time
# warning to be displayed
warning = "⚠️ It has been <i>%d</i> days since the last update, the content of the article may be outdated."

# https://utteranc.es
[params.utterances]
enable = false # whether to enable utterances
# paste utterances' <script></script> configuration between the triple quotes
script = """
"""
